<a href="https://colab.research.google.com/github/naikkrevathi/Movie-Recommedation-System/blob/main/Movei.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Movies%20Recommendation.csv')
df.head()

,Movie_ID,Movie_Title,Movie_Genre,Movie_Language,Movie_Budget,Movie_Popularity,Movie_Release_Date,Movie_Revenue,Movie_Runtime,Movie_Vote,...,Movie_Homepage,Movie_Keywords,Movie_Overview,Movie_Production_House,Movie_Production_Country,Movie_Spoken_Language,Movie_Tagline,Movie_Cast,Movie_Crew,Movie_Director
0,1,Four Rooms,Crime Comedy,en,4000000,22.876230,09-12-1995,4300000,98.0,6.5,...,NaN,hotel new year's eve witch bet hotel room,It's Ted the Bellhop's first night on the job....,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Twelve outrageous guests. Four scandalous requ...,Tim Roth Antonio Banderas Jennifer Beals Madon...,"[{'name': 'Allison Anders', 'gender': 1, 'depa...",Allison Anders
1,2,Star Wars,Adventure Action Science Fiction,en,11000000,126.393695,25-05-1977,775398007,121.0,8.1,...,http://www.starwars.com/films/star-wars-episod...,android galaxy hermit death star lightsaber,Princess Leia is captured and held hostage by ...,"[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twe...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","A long time ago in a galaxy far, far away...",Mark Hamill Harrison Ford Carrie Fisher Peter ...,"[{'name': 'George Lucas', 'gender': 2, 'depart...",George Lucas
2,3,Finding Nemo,Animation Family,en,94000000,85.688789,30-05-2003,940335536,100.0,7.6,...,http://movies.disney.com/finding-nemo,father son relationship harbor underwater fish...,"Nemo, an adventurous young clownfish, is unexp...","[{""name"": ""Pixar Animation Studios"", ""id"": 3}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","There are 3.7 trillion fish in the ocean, they...",Albert Brooks Ellen DeGeneres Alexander Gould ...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
3,4,Forrest Gump,Comedy Drama Romance,en,55000000,138.133331,06-07-1994,677945399,142.0,8.2,...,NaN,vietnam veteran hippie mentally disabled runni...,A man with a low IQ has accomplished great thi...,"[{""name"": ""Paramount Pictures"", ""id"": 4}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","The world will never be the same, once you've ...",Tom Hanks Robin Wright Gary Sinise Mykelti Wil...,"[{'name': 'Alan Silvestri', 'gender': 2, 'depa...",Robert Zemeckis
4,5,American Beauty,Drama,en,15000000,80.878605,15-09-1999,356296601,122.0,7.9,...,http://www.dreamworks.com/ab/,male nudity female nudity adultery midlife cri...,"Lester Burnham, a depressed suburban father in...","[{""name"": ""DreamWorks SKG"", ""id"": 27}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Look closer.,Kevin Spacey Annette Bening Thora Birch Wes Be...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes

In [ ]:
df.info()
df.shape
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4760 entries, 0 to 4759
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Movie_ID                  4760 non-null   int64
 1   Movie_Title               4760 non-null   object
 2   Movie_Genre               4760 non-null   object
 3   Movie_Language            4760 non-null   object
 4   Movie_Budget              4760 non-null   int64
 5   Movie_Popularity          4760 non-null   float64
 6   Movie_Release_Date        4760 non-null   object
 7   Movie_Revenue             4760 non-null   int64
 8   Movie_Runtime             4758 non-null   float64
 9   Movie_Vote                4760 non-null   float64
 10  Movie_Vote_Count          4760 non-null   int64
 11  Movie_Homepage            1699 non-null   object
 12  Movie_Keywords            4373 non-null   object
 13  Movie_Overview            4757 non-null   object
 14  Movie_Production_House    4760 non-null   object
 15  Movie_Production_Country  4760 non-null   object
 16  Movie_Spoken_Language     4760 non-null   object
 17  Movie_Tagline             3942 non-null   object
 18  Movie_Cast                4733 non-null   object
 19  Movie_Crew                4760 non-null   object
 20  Movie_Director            4738 non-null   object
dtypes: float64(3), int64(4), object(14)
memory usage: 781.1+ KB

Index(['Movie_ID', 'Movie_Title', 'Movie_Genre', 'Movie_Language',
       'Movie_Budget', 'Movie_Popularity', 'Movie_Release_Date',
       'Movie_Revenue', 'Movie_Runtime', 'Movie_Vote', 'Movie_Vote_Count',
       'Movie_Homepage', 'Movie_Keywords', 'Movie_Overview',
       'Movie_Production_House', 'Movie_Production_Country',
       'Movie_Spoken_Language', 'Movie_Tagline', 'Movie_Cast', 'Movie_Crew',
       'Movie_Director'],
      dtype='object')

In [ ]:
df_features=df[['Movie_Genre','Movie_Keywords','Movie_Tagline','Movie_Cast','Movie_Director']].fillna(' ')

In [ ]:
df_features.shape

(4760, 5)

In [ ]:
df_features

,Movie_Genre,Movie_Keywords,Movie_Tagline,Movie_Cast,Movie_Director
0,Crime Comedy,hotel new year's eve witch bet hotel room,Twelve outrageous guests. Four scandalous requ...,Tim Roth Antonio Banderas Jennifer Beals Madon...,Allison Anders
1,Adventure Action Science Fiction,android galaxy hermit death star lightsaber,"A long time ago in a galaxy far, far away...",Mark Hamill Harrison Ford Carrie Fisher Peter ...,George Lucas
2,Animation Family,father son relationship harbor underwater fish...,"There are 3.7 trillion fish in the ocean, they...",Albert Brooks Ellen DeGeneres Alexander Gould ...,Andrew Stanton
3,Comedy Drama Romance,vietnam veteran hippie mentally disabled runni...,"The world will never be the same, once you've ...",Tom Hanks Robin Wright Gary Sinise Mykelti Wil...,Robert Zemeckis
4,Drama,male nudity female nudity adultery midlife cri...,Look closer.,Kevin Spacey Annette Bening Thora Birch Wes Be...,Sam Mendes
...,...,...,...,...,...
4755,Horror,,The hot spot where Satan's waitin'.,Lisa Hart Carroll Michael Des Barres Paul Drak...,Pece Dingo
4756,Comedy Family Drama,,It’s better to stand out than to fit in.,Roni Akurati Brighton Sharbino Jason Lee Anjul...,Frank Lotito
4757,Thriller Drama,christian film sex trafficking,She never knew it could happen to her...,Nicole Smolen Kim Baldwin Ariana Stephens Brys...,Jaco Booyens
4758,Family,,,,
4759,Documentary,music actors legendary perfomer classic hollyw...,,Tony Oppedisano,Simon Napier-Bell

In [ ]:
x=df_features['Movie_Genre']+' '+df_features['Movie_Keywords']+' '+df_features['Movie_Tagline']+' '+df_features['Movie_Cast']+' '+df_features['Movie_Director']
x.shape

(4760,)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf =TfidfVectorizer()
X=tfidf.fit_transform(x)

In [ ]:
X.shape
print(X)

  (0, 617)	0.1633382144407513
  (0, 492)	0.1432591540388685
  (0, 15413)	0.1465525095337543
  (0, 9675)	0.14226057295252661
  (0, 9465)	0.1659841367820977
  (0, 1390)	0.16898383612799558
  (0, 7825)	0.09799561597509843
  (0, 1214)	0.13865857545144072
  (0, 729)	0.13415063359531618
  (0, 13093)	0.1432591540388685
  (0, 15355)	0.10477815972666779
  (0, 9048)	0.0866842116160778
  (0, 11161)	0.06250380151644369
  (0, 16773)	0.17654247479915475
  (0, 5612)	0.08603537588547631
  (0, 16735)	0.10690083751525419
  (0, 7904)	0.13348000542112332
  (0, 15219)	0.09800472886453934
  (0, 11242)	0.07277788238484746
  (0, 3878)	0.11998399582562203
  (0, 5499)	0.11454057510303811
  (0, 7071)	0.19822417598406614
  (0, 7454)	0.14745635785412262
  (0, 1495)	0.19712637387361423
  (0, 9206)	0.15186283580984414
  :	:
  (4757, 5455)	0.12491480594769522
  (4757, 2967)	0.16273475835631626
  (4757, 8464)	0.23522565554066333
  (4757, 6938)	0.17088173678136628
  (4757, 8379)	0.17480603856721913
  (4757, 15303)	0.07654356007668191
  (4757, 15384)	0.09754322497537371
  (4757, 7649)	0.11479421494340192
  (4757, 10896)	0.14546473055066447
  (4757, 4494)	0.05675298448720501
  (4758, 5238)	1.0
  (4759, 11264)	0.33947721804318337
  (4759, 11708)	0.33947721804318337
  (4759, 205)	0.3237911628497312
  (4759, 8902)	0.3040290704566037
  (4759, 14062)	0.3237911628497312
  (4759, 3058)	0.2812896191863103
  (4759, 7130)	0.26419662449963793
  (4759, 10761)	0.3126617295732147
  (4759, 4358)	0.18306542312175342
  (4759, 14051)	0.20084315377640435
  (4759, 5690)	0.19534291014627303
  (4759, 15431)	0.19628653185946862
  (4759, 1490)	0.21197258705292082
  (4759, 10666)	0.15888268987343043

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
Similarity_Score=cosine_similarity(X)
Similarity_Score

array([[1.        , 0.01351235, 0.03570468, ..., 0.        , 0.        ,
        0.        ],
       [0.01351235, 1.        , 0.00806674, ..., 0.        , 0.        ,
        0.        ],
       [0.03570468, 0.00806674, 1.        , ..., 0.        , 0.08014876,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.08014876, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [ ]:
Similarity_Score.shape

(4760, 4760)

In [ ]:
Favourite_Movie_Name=input( "Enter your favourite movie name:")
All_Movies_Title_List = df['Movie_Title'].tolist()

Enter your favourite movie name:Kadamba

In [ ]:
import difflib
Movie_Recommendation=difflib.get_close_matches(Favourite_Movie_Name, All_Movies_Title_List)
print(Movie_Recommendation)

['La Bamba', 'Khumba']

In [ ]:
Close_Match=Movie_Recommendation[0]
print(Close_Match)

La Bamba

In [ ]:
Index_of_Close_Match_Movie= df[df.Movie_Title==Close_Match] ['Movie_ID'].values[0]
print(Index_of_Close_Match_Movie)

2527

In [ ]:
Recommendation_Score=list(enumerate(Similarity_Score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)
len(Recommendation_Score)

[(0, 0.0), (1, 0.04423060931222241), (2, 0.0), (3, 0.04064838692182392), (4, 0.002650423260307818), (5, 0.0025194463468388726), (6, 0.03945357175990319), (7, 0.014074902819594684), (8, 0.041768255642881925), (9, 0.018127141152157498), (10, 0.0), (11, 0.0026012476074330996), (12, 0.0026824880000092034), (13, 0.011073084999734684), (14, 0.0), (15, 0.02358543033411592), (16, 0.0020936976199264993), (17, 0.03921678736787881), (18, 0.015970197043895146), (19, 0.018903856085846382), (20, 0.002627435306300607), (21, 0.002686267104668159), (22, 0.01696014060804146), (23, 0.008846782026607627), (24, 0.2705396794941574), (25, 0.0020779009281701923), (26, 0.0024578326992570547), (27, 0.017743374609905344), (28, 0.037230761587818566), (29, 0.013776758640037719), (30, 0.03287501835041769), (31, 0.018426691468853132), (32, 0.013753348649754232), (33, 0.0075025518982014755), (34, 0.002613880366422973), (35, 0.0), (36, 0.0), (37, 0.04252330517174049), (38, 0.0), (39, 0.0436020407313654), (40, 0.0), (41, 0.017451174735392806), (42, 0.0), (43, 0.02562302614487174), (44, 0.0020910365031142717), (45, 0.07401945642114212), (46, 0.031983066444332756), (47, 0.0), (48, 0.002767817150058965), (49, 0.005793954853893928), (50, 0.029597524205767282), (51, 0.03565952128201382), (52, 0.0024018090763089834), (53, 0.018561723957036154), (54, 0.019892873582462025), (55, 0.02046773960464809), (56, 0.019943702830761575), (57, 0.016155078965626932), (58, 0.016424584741819945), (59, 0.0), (60, 0.05094119112842737), (61, 0.07927769591644696), (62, 0.009372874851406582), (63, 0.006756509322033796), (64, 0.014306081296394125), (65, 0.016938593993423172), (66, 0.019803067226290674), (67, 0.01548898409418578), (68, 0.037263881631765965), (69, 0.018755062695001292), (70, 0.0), (71, 0.028764813395661393), (72, 0.0), (73, 0.04303264490114502), (74, 0.02083791588799128), (75, 0.06322841348417663), (76, 0.025477107935786423), (77, 0.06943896592813885), (78, 0.025429748892854563), (79, 0.01953194930873472), (80, 0.015650868263773644), (81, 0.0), (82, 0.024649488367979932), (83, 0.0), (84, 0.01672443637667702), (85, 0.008166998409199003), (86, 0.0051407193217033334), (87, 0.03373918725190643), (88, 0.022046265335680895), (89, 0.0), (90, 0.01670307772753557), (91, 0.07272159525962507), (92, 0.002210633325133823), (93, 0.016360070923009288), (94, 0.01568595369610945), (95, 0.017570612074306498), (96, 0.0023248923552649727), (97, 0.01461582403391664), (98, 0.030157028181586224), (99, 0.0), (100, 0.04718407431565372), (101, 0.0), (102, 0.018661294231978216), (103, 0.007353124316138113), (104, 0.028091807492231224), (105, 0.0024912884636772987), (106, 0.0019336783724396723), (107, 0.030723709758193343), (108, 0.02486610555127844), (109, 0.0025043614799458934), (110, 0.006109171934418498), (111, 0.0023334829165935164), (112, 0.0024183617653881027), (113, 0.006981158711124421), (114, 0.008497573282399187), (115, 0.0025685459568510877), (116, 0.038931167262984845), (117, 0.01929148062510129), (118, 0.05718350202604627), (119, 0.0024644724952669365), (120, 0.0025906653307748886), (121, 0.049664004293894004), (122, 0.01804439772023934), (123, 0.03844184260916526), (124, 0.002293714281997709), (125, 0.04226431089722779), (126, 0.0023700630539764444), (127, 0.0024458866188660617), (128, 0.01894922953639284), (129, 0.005928214426350121), (130, 0.017783049225711115), (131, 0.0), (132, 0.007526539616272724), (133, 0.0), (134, 0.0), (135, 0.03022641925361244), (136, 0.020408686512274208), (137, 0.0), (138, 0.0), (139, 0.0), (140, 0.002353037094608033), (141, 0.02151554046393399), (142, 0.002078303052587218), (143, 0.023889786723609353), (144, 0.011361067415603842), (145, 0.03325821451820763), (146, 0.006447775317586721), (147, 0.0021732629287631628), (148, 0.0), (149, 0.002074352142944564), (150, 0.01672062783875156), (151, 0.01764472741277335), (152, 0.048089351149129725), (153, 0.0), (154, 0.002357885986789864), (155, 0.06797551492257929), (156, 0.006896503496925094), (157, 0.002392383004762722), (158, 0.025040414268825115), (159, 0.0019659954236511076), (160, 0.015656428103772924), (161, 0.028100784650709896), (162, 0.05734716143428638), (163, 0.0), (164, 0.0023902426647778607), (165, 0.0021715030819421752), (166, 0.057499493618817364), (167, 0.0024267129078401894), (168, 0.01111534108986409), (169, 0.008340884661427503), (170, 0.0), (171, 0.0162139497822031), (172, 0.03258554355041824), (173, 0.054987208681301025), (174, 0.008385499699173751), (175, 0.0021211203622030148), (176, 0.029050950533002665), (177, 0.01669871376548242), (178, 0.008930626004153919), (179, 0.018828349418289557), (180, 0.020932154886257093), (181, 0.019457953921029177), (182, 0.01999998958515864), (183, 0.0023037678722508895), (184, 0.0022120015089454044), (185, 0.0), (186, 0.0), (187, 0.014982622492503352), (188, 0.019460474793337613), (189, 0.03132764652649063), (190, 0.0021436203594690662), (191, 0.03271733597921352), (192, 0.009181981922478488), (193, 0.07515691030377104), (194, 0.006811330886432284), (195, 0.007135698068439169), (196, 0.002109907650500014), (197, 0.008015871067605432), (198, 0.00861360227654164), (199, 0.0022904548026266855), (200, 0.013857895965037463), (201, 0.02564229766016843), (202, 0.005570575613494353), (203, 0.0023768167476165584), (204, 0.023088787260086317), (205, 0.0), (206, 0.02344363647402998), (207, 0.0), (208, 0.00266686793998713), (209, 0.0025347274528562226), (210, 0.0027072752121341127), (211, 0.008873649259784783), (212, 0.007944866533159784), (213, 0.015501098810087212), (214, 0.0), (215, 0.0024678269325054208), (216, 0.002604252744377277), (217, 0.0), (218, 0.03765862213136476), (219, 0.0), (220, 0.018058505114959864), (221, 0.008071682811100848), (222, 0.0022109382643914588), (223, 0.0), (224, 0.006495306471158584), (225, 0.006874580976457504), (226, 0.0025116278960580604), (227, 0.009072852058871279), (228, 0.020516184677675613), (229, 0.0023418949889968226), (230, 0.019076091925213434), (231, 0.02054083954687428), (232, 0.021090286090748294), (233, 0.0), (234, 0.014700806440177508), (235, 0.059008875871128366), (236, 0.0023595350214277245), (237, 0.0), (238, 0.0484506429389248), (239, 0.0), (240, 0.10898382638223487), (241, 0.03235863836091659), (242, 0.0021748752420877276), (243, 0.0017685050633304735), (244, 0.0), (245, 0.0), (246, 0.002671417896471993), (247, 0.0731726204886425), (248, 0.0), (249, 0.08754773373619688), (250, 0.0), (251, 0.0021530162543202053), (252, 0.017355200963829438), (253, 0.0027463936628170163), (254, 0.0027687086689288346), (255, 0.008889913913015465), (256, 0.001876659559464706), (257, 0.06905994930861772), (258, 0.0479068961556228), (259, 0.016983267674526393), (260, 0.01620124333669617), (261, 0.016479962389934478), (262, 0.0026389036428041412), (263, 0.028628661415691405), (264, 0.030294075684810892), (265, 0.0), (266, 0.0019327926102066162), (267, 0.002128751852054604), (268, 0.002240432400756013), (269, 0.0021554420798534737), (270, 0.002627118069297735), (271, 0.023959276061162976), (272, 0.005975739790647001), (273, 0.024651883413605635), (274, 0.0028842510933923004), (275, 0.006321193769521761), (276, 0.0023685104817626223), (277, 0.017218503306303284), (278, 0.007311695225950187), (279, 0.007947518709393645), (280, 0.03504446164173308), (281, 0.03966534105016665), (282, 0.0024746859074396537), (283, 0.05573758286447214), (284, 0.008144934481994175), (285, 0.031653686180906845), (286, 0.0021555709446583297), (287, 0.002357030185444988), (288, 0.0), (289, 0.011351123490690847), (290, 0.0), (291, 0.0), (292, 0.048328706370877196), (293, 0.021898107182485613), (294, 0.0), (295, 0.0), (296, 0.0018826695909851046), (297, 0.020723497151378167), (298, 0.020462170723506118), (299, 0.019585184024652078), (300, 0.018661865799354978), (301, 0.020720762903951088), (302, 0.00543289982034064), (303, 0.053735410957425525), (304, 0.0), (305, 0.0), (306, 0.030058667077014115), (307, 0.018378173937319886), (308, 0.002808968127379457), (309, 0.006752312827280888), (310, 0.0), (311, 0.0), (312, 0.006018887237257022), (313, 0.0), (314, 0.014318593910912369), (315, 0.0), (316, 0.030063689830115085), (317, 0.0021995411166731505), (318, 0.01581003620075031), (319, 0.0), (320, 0.03420189084772055), (321, 0.0), (322, 0.0), (323, 0.0), (324, 0.015350560709008445), (325, 0.00802229475358018), (326, 0.0419440986689809), (327, 0.0), (328, 0.005805459030589566), (329, 0.002436808199513664), (330, 0.021280073788561102), (331, 0.024410052451466772), (332, 0.014667100374519262), (333, 0.027773154547718518), (334, 0.02285875656693601), (335, 0.0), (336, 0.014048508272472568), (337, 0.0), (338, 0.017871425583703106), (339, 0.05034685895138267), (340, 0.021046432770233645), (341, 0.01418206034594595), (342, 0.0027364432156884557), (343, 0.04726105783102452), (344, 0.0), (345, 0.013707199163045193), (346, 0.00249605904919207), (347, 0.023136675423089975), (348, 0.002486640051643592), (349, 0.002436295416482488), (350, 0.0027346847515537696), (351, 0.0019164798241473027), (352, 0.0), (353, 0.0025512248422536288), (354, 0.012053508617592643), (355, 0.025890443639206378), (356, 0.032329140629655834), (357, 0.030159926419906228), (358, 0.03296343097753481), (359, 0.0023052513723803817), (360, 0.0), (361, 0.020793350584147243), (362, 0.05744188743614578), (363, 0.021404661175158855), (364, 0.12266882254542921), (365, 0.021752651561563977), (366, 0.0), (367, 0.043460493606954684), (368, 0.02050308289036498), (369, 0.04554440549014997), (370, 0.0025079033012023084), (371, 0.002764148612658177), (372, 0.01461286254542592), (373, 0.00804568153333999), (374, 0.0024783777858752376), (375, 0.03623962039210837), (376, 0.014837755611708968), (377, 0.002588190667287473), (378, 0.045189357525208924), (379, 0.19482157232944233), (380, 0.0488065855896564), (381, 0.01599887644639111), (382, 0.10744947207900626), (383, 0.0), (384, 0.0), (385, 0.028301587239114214), (386, 0.0), (387, 0.00236908592350559), (388, 0.008014252048194294), (389, 0.017005178791155148), (390, 0.03005226876831553), (391, 0.0), (392, 0.0), (393, 0.0), (394, 0.01459752032921448), (395, 0.037842938163924436), (396, 0.002413919917738773), (397, 0.015617621663826967), (398, 0.006019093066999034), (399, 0.0023276053165378376), (400, 0.002488908721066754), (401, 0.0397061433174118), (402, 0.003062245962147246), (403, 0.06568635641540473), (404, 0.019009521964609002), (405, 0.05233619359351582), (406, 0.008661549766253527), (407, 0.006811689699964299), (408, 0.008026425885064425), (409, 0.0), (410, 0.0210558998852969), (411, 0.030069087460198957), (412, 0.0020522160253718057), (413, 0.018239606269197635), (414, 0.014709822394820804), (415, 0.020689848474056777), (416, 0.0023019038352110706), (417, 0.0), (418, 0.0), (419, 0.002829141947543485), (420, 0.015207943388599869), (421, 0.0), (422, 0.0), (423, 0.0), (424, 0.0), (425, 0.0), (426, 0.028032644107891688), (427, 0.033006308211224536), (428, 0.002267895396152459), (429, 0.03662885480808268), (430, 0.04217200477454074), (431, 0.01001187469968629), (432, 0.03823191818633754), (433, 0.01282887565974459), (434, 0.044941100558872155), (435, 0.0), (436, 0.0028104658504449352), (437, 0.002383516567487123), (438, 0.013963909567650428), (439, 0.01698054717054638), (440, 0.01383836407294189), (441, 0.0020758053201954388), (442, 0.0020828594648417127), (443, 0.07002260020332726), (444, 0.03678383143391968), (445, 0.0021504230502189946), (446, 0.002450448177395413), (447, 0.03372892576441803), (448, 0.09726426854008047), (449, 0.002271856237968198), (450, 0.002756357926862234), (451, 0.01967295718205466), (452, 0.001891938250482773), (453, 0.014982158488985719), (454, 0.0), (455, 0.018321425610325064), (456, 0.043702968290380874), (457, 0.0023055135320807843), (458, 0.0028028731087784108), (459, 0.0), (460, 0.01700167555544834), (461, 0.0), (462, 0.0), (463, 0.0023280231562637227), (464, 0.008391454078312311), (465, 0.007750515426738395), (466, 0.002483450847464091), (467, 0.06300074118365805), (468, 0.013234451682164767), (469, 0.026807472538164144), (470, 0.01654096703019754), (471, 0.007927966441252408), (472, 0.02632497857199015), (473, 0.0022726017942242796), (474, 0.006280883734214858), (475, 0.0029678408532979646), (476, 0.0172157046520525), (477, 0.0), (478, 0.03159329614188504), (479, 0.0025090061259738674), (480, 0.01939298220031944), (481, 0.017055748321046102), (482, 0.0026219233160760624), (483, 0.050156246093047675), (484, 0.04324334266442785), (485, 0.034809942888450914), (486, 0.0), (487, 0.002404656822496549), (488, 0.008211479989637522), (489, 0.010155565777415741), (490, 0.008406562617039698), (491, 0.042868883752885945), (492, 0.03423601266272387), (493, 0.029811395264895523), (494, 0.0), (495, 0.01954689393390289), (496, 0.0021445956712062056), (497, 0.015200263525466044), (498, 0.10508290099403933), (499, 0.002733697110578218), (500, 0.0), (501, 0.0), (502, 0.0026297553865484427), (503, 0.0), (504, 0.008540804313470166), (505, 0.033202109063948826), (506, 0.0), (507, 0.002358671671175175), (508, 0.0028883391489461082), (509, 0.02009305366184612), (510, 0.006785983774382009), (511, 0.015556380039596807), (512, 0.0), (513, 0.0), (514, 0.0), (515, 0.0022642600774890756), (516, 0.017804677055132234), (517, 0.017750720959900792), (518, 0.002944859296660712), (519, 0.0022179385234895378), (520, 0.005222862261412435), (521, 0.013616833440223665), (522, 0.021452778116817436), (523, 0.0), (524, 0.032309000747437575), (525, 0.0), (526, 0.003158763522788495), (527, 0.001988640145162719), (528, 0.01994530188691213), (529, 0.006014472032947023), (530, 0.0), (531, 0.00717685999151017), (532, 0.0), (533, 0.03951953792572696), (534, 0.0024809828687493898), (535, 0.0), (536, 0.0), (537, 0.07136009405932127), (538, 0.02108913746263191), (539, 0.0), (540, 0.0), (541, 0.0024297100362563966), (542, 0.03370109415461519), (543, 0.03640120199824146), (544, 0.002549126713533037), (545, 0.06613052900118206), (546, 0.09153270972040646), (547, 0.0071575760185315085), (548, 0.0), (549, 0.0), (550, 0.0), (551, 0.002608792072230408), (552, 0.0), (553, 0.012147252691065015), (554, 0.01656927633451406), (555, 0.028098738970410753), (556, 0.0), (557, 0.0), (558, 0.01829645315973697), (559, 0.0), (560, 0.0), (561, 0.012595648528063576), (562, 0.03650750057491553), (563, 0.02601889432969838), (564, 0.008894015313535883), (565, 0.02916344708037935), (566, 0.0021074466892224693), (567, 0.0166567824209078), (568, 0.03633521954121833), (569, 0.017948177382548176), (570, 0.026754911788997703), (571, 0.0019367696855411357), (572, 0.017510682835288397), (573, 0.0), (574, 0.0), (575, 0.011049577446206842), (576, 0.00957008483947553), (577, 0.038638737790939556), (578, 0.0023707870942905164), (579, 0.008605806652746652), (580, 0.02917064892226678), (581, 0.002263689234413388), (582, 0.0070420125806371645), (583, 0.005418955642294776), (584, 0.016227896217180883), (585, 0.0), (586, 0.020404662740210112), (587, 0.00933659712233987), (588, 0.022508384902524013), (589, 0.007867822602305553), (590, 0.0023151934599231795), (591, 0.018758323264241154), (592, 0.019895269525342242), (593, 0.002562131754672724), (594, 0.0022452437984823988), (595, 0.0), (596, 0.002814542479228382), (597, 0.0022580669086637935), (598, 0.0023404609343710124), (599, 0.017969991064824314), (600, 0.01797339747684845), (601, 0.014571545303609055), (602, 0.013946113205061974), (603, 0.018167804509787742), (604, 0.002310238294801645), (605, 0.044803953730875035), (606, 0.026404771391090272), (607, 0.006541702700316284), (608, 0.007695492603850731), (609, 0.017957368992564258), (610, 0.01947579042366303), (611, 0.004035845939537666), (612, 0.009013524824919069), (613, 0.11083557794135612), (614, 0.022480158331396303), (615, 0.020291242378472067), (616, 0.03583183089003768), (617, 0.04078571844901248), (618, 0.005835555901624093), (619, 0.01700190636732791), (620, 0.0024126611054033444), (621, 0.01114412094117122), (622, 0.0026691840844647497), (623, 0.009016521327814383), (624, 0.002297635259328097), (625, 0.06478259621687196), (626, 0.0021287827703058435), (627, 0.00340141896345412), (628, 0.0025326268203259296), (629, 0.0), (630, 0.0), (631, 0.0025827818669898785), (632, 0.0), (633, 0.016977367110928947), (634, 0.012939045239422456), (635, 0.021386121062265298), (636, 0.0200386100750134), (637, 0.002601257452453744), (638, 0.007824444122785133), (639, 0.01654075157034403), (640, 0.016398470133808185), (641, 0.001798818663365145), (642, 0.02184062838194512), (643, 0.0966567135525081), (644, 0.02667275002287485), (645, 0.0020516325323102504), (646, 0.002415644442098157), (647, 0.0022040070763548057), (648, 0.021283079341283415), (649, 0.036407892598028714), (650, 0.0), (651, 0.0024251869135926566), (652, 0.0025693620343442873), (653, 0.013645342735685018), (654, 0.0), (655, 0.09667248021207486), (656, 0.03178278150354368), (657, 0.01478990764755905), (658, 0.0), (659, 0.0023398810279140207), (660, 0.008867960388170809), (661, 0.0), (662, 0.032704722198582746), (663, 0.04761488699960858), (664, 0.0), (665, 0.005990869742856354), (666, 0.01922101753779974), (667, 0.0), (668, 0.021609399909847646), (669, 0.002311297287679214), (670, 0.003095720721459355), (671, 0.0061723011737985865), (672, 0.00223992830932858), (673, 0.0027412190226751465), (674, 0.03634954778013992), (675, 0.0027393962946276416), (676, 0.002435298509657968), (677, 0.0), (678, 0.03536321432661315), (679, 0.0), (680, 0.0026714395383142914), (681, 0.09278850521197096), (682, 0.0), (683, 0.0028358321732340364), (684, 0.006229476652497619), (685, 0.0), (686, 0.09775700044272403), (687, 0.0), (688, 0.002782688094080008), (689, 0.0024981947048167536), (690, 0.0), (691, 0.002030228841793021), (692, 0.0), (693, 0.008262766633171555), (694, 0.0023621887550951963), (695, 0.0), (696, 0.019971850633715725), (697, 0.008524987706339787), (698, 0.008032128027738842), (699, 0.11690160799022947), (700, 0.02804939068636098), (701, 0.002804055969538925), (702, 0.015980933911522898), (703, 0.02494089245946061), (704, 0.035276009104806876), (705, 0.00751575901372176), (706, 0.0656861032786389), (707, 0.014008474883748621), (708, 0.0), (709, 0.005005408320624005), (710, 0.0), (711, 0.0), (712, 0.019525484098100416), (713, 0.018649184555542916), (714, 0.024868052554062665), (715, 0.024387520658027625), (716, 0.002634146710641523), (717, 0.002619567653142894), (718, 0.01712045958851072), (719, 0.002018064923931771), (720, 0.018839516827779047), (721, 0.0028781869804946404), (722, 0.022719976963754926), (723, 0.0), (724, 0.01945326984360519), (725, 0.044531404871114955), (726, 0.04192748501631037), (727, 0.030258309607339884), (728, 0.002709326919558664), (729, 0.0028011322302889394), (730, 0.0), (731, 0.0024028841994843653), (732, 0.0022424372908706677), (733, 0.022124351187264163), (734, 0.0023525354384337977), (735, 0.011592424530784674), (736, 0.08112154671590943), (737, 0.009575251573739873), (738, 0.011650939611542618), (739, 0.017896108219367296), (740, 0.011172796508670802), (741, 0.0056758784803263625), (742, 0.0023612477707394127), (743, 0.0025812812078312946), (744, 0.015402227404871436), (745, 0.028869061484965132), (746, 0.016923022982333596), (747, 0.01904368505167526), (748, 0.03442106801900824), (749, 0.0025134823184365693), (750, 0.019960910496211962), (751, 0.044249422825471285), (752, 0.020498382091211288), (753, 0.0), (754, 0.006404015123506529), (755, 0.002441204741836672), (756, 0.014999131535660713), (757, 0.02594657406572161), (758, 0.00602389518131896), (759, 0.002287076313877645), (760, 0.006857300399659405), (761, 0.0025123453298473695), (762, 0.014805513410862432), (763, 0.04044509639136372), (764, 0.00872385716544861), (765, 0.0), (766, 0.0023242646101295644), (767, 0.0023828661285841377), (768, 0.006097963822308894), (769, 0.044759641104102396), (770, 0.048225611641500236), (771, 0.0), (772, 0.0), (773, 0.050084308215722184), (774, 0.05598961740689977), (775, 0.0), (776, 0.015590046484925086), (777, 0.023847592018444018), (778, 0.050961459594130704), (779, 0.

4760

In [ ]:
Sorted_Similar_Movies=sorted(Recommendation_Score, key=lambda x:x[1], reverse= True)
print(Sorted_Similar_Movies)

[(2527, 1.0000000000000002), (3480, 0.27625143915277495), (24, 0.2705396794941574), (3566, 0.20107066183488656), (379, 0.19482157232944233), (1801, 0.19059583768834265), (1730, 0.1795846695894156), (3270, 0.15233076919067912), (4034, 0.1513368954822404), (4339, 0.12802800095245617), (2222, 0.12750949267679149), (3115, 0.12442298852980421), (3468, 0.12328994610714687), (364, 0.12266882254542921), (2038, 0.12231732065838663), (1137, 0.12116176156874797), (699, 0.11690160799022947), (1111, 0.11490725983893149), (3389, 0.11349321515553552), (1758, 0.11243733703347734), (613, 0.11083557794135612), (240, 0.10898382638223487), (2804, 0.10775099104100117), (382, 0.10744947207900626), (3559, 0.1067058960935659), (2033, 0.10626286338443358), (3459, 0.10615191078812872), (498, 0.10508290099403933), (4273, 0.10207169104609057), (1669, 0.1011199251982589), (4054, 0.10086209620459094), (3966, 0.10063537833644454), (1051, 0.10050951339259699), (3091, 0.09988471136573147), (3935, 0.09976002954352453), (3323, 0.09939999998799066), (1652, 0.09777021910998315), (686, 0.09775700044272403), (2998, 0.09774242961633882), (448, 0.09726426854008047), (2955, 0.09687702613152226), (655, 0.09667248021207486), (643, 0.0966567135525081), (1573, 0.09579088875184447), (1459, 0.09570979513237715), (854, 0.09519309116243482), (4070, 0.0948855237897614), (1903, 0.094335972686611), (1354, 0.09320847471430894), (4388, 0.09320757137973516), (681, 0.09278850521197096), (3513, 0.0925218757950496), (1341, 0.09228975188530639), (2404, 0.092164112465015), (2355, 0.09189826799139134), (546, 0.09153270972040646), (3141, 0.09139889195386694), (3889, 0.09084903714721407), (3140, 0.08945950178987472), (1723, 0.08921314942514337), (249, 0.08754773373619688), (1533, 0.08751735006539435), (3282, 0.08716303224077171), (3633, 0.08708357852150617), (1046, 0.08640742762415066), (2483, 0.08604965044689043), (874, 0.08601867922006115), (3388, 0.08535791342184279), (3714, 0.08502889224070764), (1050, 0.08497623786160832), (2652, 0.08472767326992438), (1926, 0.08265607617521809), (2233, 0.08261229661829447), (4483, 0.08180027823576518), (1566, 0.08132248851006932), (1965, 0.08124998314508841), (2009, 0.08121634855485846), (736, 0.08112154671590943), (844, 0.07975541596869265), (61, 0.07927769591644696), (1055, 0.07779940726190164), (2018, 0.07737992391541293), (3299, 0.07730510163438808), (4487, 0.07664126680518378), (3871, 0.07550496972316534), (3878, 0.07544955895559002), (193, 0.07515691030377104), (3355, 0.07507129225051348), (914, 0.074887000178469), (4440, 0.07466584604274075), (2058, 0.0741279766823476), (45, 0.07401945642114212), (3783, 0.07368624161552807), (1351, 0.07356001455339212), (247, 0.0731726204886425), (1946, 0.07304565382169867), (91, 0.07272159525962507), (2505, 0.07230571202561882), (2430, 0.07212065358996073), (3605, 0.07196554952043067), (3541, 0.07150486668289527), (4446, 0.07142122337201366), (537, 0.07136009405932127), (2940, 0.07111124557856313), (3064, 0.07084413387152218), (803, 0.07062550269600039), (1414, 0.07058120338517498), (3227, 0.07009423822339926), (443, 0.07002260020332726), (4100, 0.06983041052113334), (77, 0.06943896592813885), (2114, 0.0694257963987099), (257, 0.06905994930861772), (1925, 0.06808343017102403), (2740, 0.06800015073459088), (155, 0.06797551492257929), (2547, 0.06756303697817331), (3517, 0.06741218768469767), (1472, 0.0671026096684979), (2721, 0.06639685544195961), (545, 0.06613052900118206), (3364, 0.06582823264477658), (1195, 0.06571762637267933), (403, 0.06568635641540473), (706, 0.0656861032786389), (3670, 0.06566350956400249), (1664, 0.06562766399471022), (2605, 0.06544241693876643), (1191, 0.06536367555769422), (2042, 0.06531722012380403), (2027, 0.06518308096218497), (1906, 0.06509674683116173), (2177, 0.06487816056254057), (3611, 0.0648328306232351), (625, 0.06478259621687196), (3492, 0.06447709996943049), (2240, 0.06438246106174846), (2326, 0.06435564435213681), (3405, 0.0643018737299857), (1948, 0.06362806664414292), (75, 0.06322841348417663), (3147, 0.06315853085664937), (2748, 0.06308528977020629), (2296, 0.06304713482891139), (467, 0.06300074118365805), (3028, 0.06291588912076557), (4162, 0.06278402384388698), (1845, 0.0624056048001093), (3276, 0.06206301473280217), (1072, 0.06185689815533361), (2329, 0.06139658932200123), (2720, 0.06127349861766963), (1307, 0.06122795541600215), (1364, 0.060239196697019104), (2500, 0.059501781740556224), (235, 0.059008875871128366), (1261, 0.058771835936219465), (2514, 0.058620635658911964), (2136, 0.058523638095992564), (1902, 0.058079778519901606), (2997, 0.058019070668913576), (2695, 0.05798121061536535), (1171, 0.05795872221154032), (1376, 0.05783764057187349), (1738, 0.05782370232887904), (166, 0.057499493618817364), (362, 0.05744188743614578), (162, 0.05734716143428638), (4421, 0.05730319456885178), (118, 0.05718350202604627), (3496, 0.056804998740772474), (1792, 0.05676994766817887), (1613, 0.0561676121524226), (1519, 0.056140939812967985), (1317, 0.05607875322175124), (3298, 0.05603517742314192), (774, 0.05598961740689977), (3051, 0.055889764251449835), (283, 0.05573758286447214), (2073, 0.055583958012397044), (3143, 0.05550051964896558), (2819, 0.05545443089669255), (3018, 0.05520647030455017), (3691, 0.05508135548288994), (1619, 0.055034260365704815), (1759, 0.05503132024939978), (173, 0.054987208681301025), (1089, 0.05492115773193571), (2711, 0.05477581291987839), (1486, 0.0547399479828923), (4378, 0.05465949674057169), (3205, 0.054494807301149875), (3343, 0.05419131918519181), (2456, 0.05388950989690644), (2563, 0.0538464643796132), (1265, 0.05382017461470968), (303, 0.053735410957425525), (806, 0.05367813333348924), (1045, 0.05353901465394068), (3940, 0.05348892287389448), (2665, 0.05342065609288233), (3859, 0.05333317620256455), (880, 0.05306505905464973), (1155, 0.05295845511270795), (2111, 0.05293087208927221), (2091, 0.05275557276060547), (2277, 0.05274355287801415), (1858, 0.0526628827213927), (2269, 0.052412074867394964), (405, 0.05233619359351582), (1615, 0.052301671749544774), (3408, 0.052222875655687714), (4578, 0.052137904099790536), (3777, 0.052066861342980636), (2213, 0.05164169023349761), (1253, 0.051484047981215975), (2022, 0.0514517063845399), (2944, 0.05144842032328978), (3463, 0.05141380962316179), (930, 0.051362103433008385), (4745, 0.05104968114109291), (778, 0.050961459594130704), (60, 0.05094119112842737), (1361, 0.05049053476889835), (2421, 0.050454384590303374), (339, 0.05034685895138267), (4581, 0.05030501670052069), (1541, 0.05027566166919354), (1991, 0.050234795252196596), (3900, 0.05021182647006917), (483, 0.050156246093047675), (3786, 0.050097659734344255), (773, 0.050084308215722184), (2286, 0.05007218849455369), (2733, 0.04997854430571442), (2415, 0.04988878275863641), (4152, 0.04981963006542071), (1335, 0.04976995361109449), (121, 0.049664004293894004), (1140, 0.049598660761596775), (3698, 0.049352669902754165), (3370, 0.049202237741633015), (4492, 0.04919517956121951), (2354, 0.04914218804042036), (3529, 0.04911606580943783), (2899, 0.049086467269613465), (952, 0.04902645586065961), (380, 0.0488065855896564), (238, 0.0484506429389248), (2824, 0.04842532185295578), (3218, 0.048407300028097636), (4082, 0.048383879679976316), (292, 0.048328706370877196), (1345, 0.04829904821803983), (2715, 0.04827409434394812), (770, 0.048225611641500236), (1477, 0.048163193328818556), (152, 0.048089351149129725), (2653, 0.04806824261511113), (258, 0.0479068961556228), (4334, 0.047876769586361986), (3979, 0.04776812412580802), (3272, 0.04773633303920296), (4277, 0.04764332039770361), (663, 0.04761488699960858), (3965, 0.047600068015263695), (1405, 0.04734372258934726), (343, 0.04726105783102452), (4478, 0.04721877558167066), (100, 0.04718407431565372), (961, 0.0469193838364467), (1743, 0.04687567236824157), (4695, 0.04682508899003461), (1392, 0.046767944716266045), (3133, 0.04654507603648254), (1763, 0.04627383931128197), (3357, 0.046204626942656556), (1489, 0.04619817891714975), (4007, 0.04612472417735302), (2074, 0.04609411382163149), (3789, 0.04597773846966112), (4480, 0.045935349943246884), (4099, 0.045918946404643404), (4085, 0.04574120078845702), (3219, 0.04567474019270495), (1049, 0.04560481430936935), (4021, 0.045597345391286626), (369, 0.04554440549014997), (2666, 0.045521727334067806), (4654, 0.045450187768960176), (2086, 0.0454213703331704), (2001, 0.04541830243958678), (4516, 0.045214516686663625), (378, 0.045189357525208924), (1651, 0.045104736576204674), (434, 0.044941100558872155), (4073, 0.04491375208904834), (1292, 0.044857266411723454), (605, 0.044803953730875035), (2521, 0.04479980531822374), (769, 0.044759641104102396), (2571, 0.04475432021710975), (1980, 0.04467813869615614), (2530, 0.0446579878326932), (1897, 0.044577451203839824), (3089, 0.04455306662068324), (1750, 0.044542298517381604), (725, 0.044531404871114955), (2927, 0.04443661105863412), (751, 0.044249422825471285), (3798, 0.04423649263970706), (1, 0.04423060931222241), (2837, 0.044176409567881776), (2178, 0.044127466381237074), (2095, 0.04404859336200456), (3042, 0.044011806386799836), (3470, 0.043973807803163616), (2657, 0.043900650865188205), (1245, 0.04377414207101922), (1590, 0.04376718877754959), (456, 0.043702968290380874), (3204, 0.04367203375245487), (39, 0.0436020407313654), (1833, 0.043600747701744075), (998, 0.04359957433379901), (794, 0.04350963884056826), (3579, 0.04346285623939027), (367, 0.043460493606954684), (3538, 0.04339017545568257), (3467, 0.04338902149210426), (2877, 0.043256993317809384), (2221, 0.043255736098857425), (3027, 0.04324624111038564), (484, 0.04324334266442785), (4468, 0.043236288602665617), (4298, 0.04310575443132707), (2607, 0.04305688655403989), (1466, 0.043037909239880406), (73, 0.04303264490114502), (2420, 0.04303053359323796), (3556, 0.04297091739409846), (491, 0.042868883752885945), (3845, 0.04268971732825712), (4667, 0.04265268268810671), (3710, 0.042634372724238444), (4346, 0.04254259165814933), (37, 0.04252330517174049), (2340, 0.04251788850758101), (2709, 0.04244727879660783), (2454, 0.04242814572724776), (4546, 0.0423514099193332), (125, 0.04226431089722779), (982, 0.04225902678583021), (430, 0.04217200477454074), (994, 0.04211676025880771), (1264, 0.042100255808735644), (1768, 0.04207955673706977), (4725, 0.0420064832085161), (326, 0.0419440986689809), (726, 0.04192748501631037), (1616, 0.04188860178173881), (1913, 0.041804450726297994), (889, 0.041803971362888506), (8, 0.041768255642881925), (1061, 0.04148503378044233), (897, 0.04142653437414425), (1968, 0.04142192762661593), (1567, 0.04131554610288887), (4694, 0.0412841710530182), (898, 0.04125461510520101), (2656, 0.04119131705329857), (2492, 0.04118398060540619), (1677, 0.04114647357643984), (2770, 0.04110313151636912), (3385, 0.04109825958140728), (1433, 0.04109349143891128), (1088, 0.04108262214355177), (1069, 0.04102722396004897), (1320, 0.04084102383391145), (3450, 0.040807264384607016), (617, 0.04078571844901248), (2843, 0.04072010865024207), (1836, 0.040714330251119916), (3, 0.04064838692182392), (3477, 0.040583891249661316), (763, 0.04044509639136372), (1256, 0.040266554646287485), (4375, 0.0401540098469195), (3998, 0.04013394713370198), (3886, 0.04000742497418888), (4191, 0.04000570166094569), (977, 0.039998360115575546), (3102, 0.03992846754699653), (4676, 0.039802460887444546), (4092, 0.03976243376531006), (401, 0.0397061433174118), (4319, 0.03967644806699016), (281, 0.03966534105016665), (2096, 0.03962006534373471), (3240, 0.039589720815431606), (919, 0.039563625033727616), (1150, 0.039551188620328824), (2078, 0.03953107105327632), (533, 0.03951953792572696), (1248, 0.039501696342784505), (3079, 0.03948280384434485), (6, 0.03945357175990319), (4450, 0.03938596690500501), (17, 0.03921678736787881), (1467, 0.039209364419259325), (2840, 0.03918814287359682), (2729, 0.039121127394162736), (4397, 0.03910416473591109), (2283, 0.039077681884309975), (4570, 0.03899888562819434), (1002, 0.038995855000391745), (116, 0.038931167262984845), (4006, 0.03890875305281232), (4323, 0.038886657233746284), (2629, 0.038879175323412896), (1011, 0.03886178889666436), (2330, 0.03877048866754764), (3728, 0.03875628784629999), (4011, 0.03873926001006945), (1536, 0.03868508771440148), (1142, 0.038676230765112354), (577, 0.038638737790939556), (3013, 0.038636550859749236), (123, 0.03844184260916526), (785, 0.038438617655277466), (2542, 0.03840309090701464), (2259, 0.038379102748379024), (887, 0.038352083988398955), (932, 0.03829705429950851), (3747, 0.038265569843459635), (921, 0.03826399688930537), (432, 0.03823191818633754), (1324, 0.038192115430757026), (2691, 0.038150246501416414), (3063, 0.03788617677291687), (395, 0.037842938163924436), (3641, 0.03784056359925449), (2774, 0.037837077987105595), (1771, 0.03776635574871193), (3191, 0.03775115408493322), (1143, 0.037739670953171524), (4401, 0.037692164054391845), (2100, 0.03767166949545358), (218, 0.03765862213136476), (1289, 0.03747160333972246), (2708, 0.03737712177762108), (1250, 0.03737450822363888), (2952, 0.037337138669379606), (3474, 0.037334360035496825), (3417, 0.037329308380117866), (2714, 0.03732928012480239), (4543, 0.03729545798299262), (4240, 0.03729335334394743), (68, 0.037263881631765965), (2439, 0.03724689289452425), (3375, 0.0372412085402262), (28, 0.037230761587818566), (2032, 0.037191495414257515), (1572, 0.03718867163815422), (2694, 0.03718509152243916), (2170, 0.037134416828866736), (4071, 0.03706805766204908), (1869, 0.037056047434922974), (1921, 0.03703822264334646), (1916, 0.0370264885942596), (1515, 0.03690834998540849), (1908, 0.036864295942318034), (3114, 0.03684372029157213), (1149, 0.03678583373731663), (444, 0.03678383143391968), (1610, 0.036764685394470274), (4017, 0.036760525859239855), (1129, 0.03668326046187185), (429, 0.03662885480808268), (4482, 0.036616177664730784), (4361, 0.03655570539780557), (562, 0.03650750057491553), (2921, 0.03650503761689548), (2859, 0.036462896377849476), (649, 0.036407892598028714), (543, 0.03640120199824146), (3880, 0.036370934658637895), (1382, 0.03635248200800586), (674, 0.03634954778013992), (568, 0.03633521954121833), (3692, 0.03632372955414259), (1666, 0.03626571133077893), (375, 0.03623962039210837), (4337, 0.03622436510218523), (3980, 0.0362239552834383), (1635, 0.036204399062800124), (2319, 0.03618524612813351), (3410, 0.036164241905909646), (2377, 0.036155945659368666), (2218, 0.03606265902415212), (2343, 0.03605675390225456), (938, 0.03603331982783932), (616, 0.03583183089003768), (3395, 0.03576440022071306), (3709, 0.035740789128326844), (3083, 0.035711395562523084), (2407, 0.03569024482789692), (51, 0.03565952128201382), (1469, 0.035623590475210055), (2633, 0.03558222032135582), (2265, 0.035569662626441075), (4625, 0.035562038209170886), (781, 0.03552347857112992), (2062, 0.03550653641185489), (2604, 0.03550410054057548), (678, 0.03536321432661315), (1600, 0.035349511864185446), (3970, 0.03530941320517671), (704, 0.035276009104806876), (4411, 0.03522230779470995), (4010, 0.035194066883829304), (865, 0.035167664067216664), (1027, 0.03516581204477607), (4090, 0.03515484089217056), (872, 0.03507618575429171), (280, 0.03504446164173308), (1711, 0.0350067621586577), (2495, 0.03494720980690595), (1634, 0.03490626966002515), (1637, 0.03484277177570053), (1164, 0.0348353975895708), (3532, 0.034831235206210405), (485, 0.034809942888450914), (2350, 0.03480962176840376), (3199, 0.034801834866405444), (2316, 0.03474535569818698), (3577, 0.034699569163143706), (1168, 0.03464956843311426), (1326, 0.03463604693012752), (4510, 0.0346274991775601), (2180, 0.034581419761616196), (2211, 0.034563311437034394), (3427, 0.034540848375002375), (3905, 0.03450944346462619), (2416, 0.034446169008019535), (748, 0.03442106801900824), (2503, 0.03436926838605392), (2650, 0.03435553156663118), (2848, 0.034272571008706766), (492, 0.03423601266272387), (2682, 0.034212174512634724), (3302, 0.034210262863508034), (959, 0.034208334559058126), (320, 0.03420189084772055), (1649, 0.03417452670153993), (4381, 0.03414342474465951), (1967, 0.03413393289105072), (4673, 0.03403117682160588), (3598, 0.034006643647534), (1268, 0.03396716712475455), (4515, 0.03394068869660717), (3469, 0.033878945639445365), (822, 0.03387400972865269), (2612, 0.033754594401150285), (2268, 0.033754277730752576), (87, 0.03373918725190643), (447, 0.03372892576441803), (1034, 0.03372765837617504), (542, 0.03370109415461519), (4347, 0.033678896164835506), (1518, 0.03367023377381933), (971, 0.03366559376615434), (2752, 0.033606181322911766), (1982, 0.033587218707194735), (2220, 0.033576700724615396), (4637, 0.03354791076507318), (3424, 0.03347667627445046), (2882, 0.03346686456548115), (1878, 0.033440115656448686), (1961, 0.03341742285584392), (3597, 0.03338882177867505), (4077, 0.0333339786787283), (877, 0.03331436153669963), (2540, 0.03331033829151564), (2847, 0.03330340401765579), (145, 0.03325821451820763), (1901, 0.03324478540349777), (1587, 0.0332088078474833), (505, 0.033202109063948826), (4380, 0.033201083475510804), (4554, 0.03318321143951717), (3869, 0.0331629972417238), (969, 0.03315436610361806), (427, 0.033006308211224536), (3819, 0.03299966598560022), (4609, 0.03298490705757634), (1512, 0.03297310175729103), (3181, 0.03296599886290954), (358, 0.03296343097753481), (1612, 0.03292765918971915), (30, 0.03287501835041769), (3246, 0.03283407311766555), (1509, 0.03283136072533756), (2815, 0.0328168743734418), (1172, 0.03279952432001282), (1793, 0.03275770605422522), (191, 0.03271733597921352), (662, 0.032704722198582746), (172, 0.03258554355041824), (2773, 0.032570789005971115), (1468, 0.03250332651755697), (846, 0.03249816682896307), (2735, 0.032441347623238366), (1455, 0.0323989099245183), (241, 0.03235863836091659), (3639, 0.03235679994106394), (356, 0.032329140629655834), (918, 0.032312864071870104), (524, 0.032309000747437575), (4288, 0.03230578872853974), (906, 0.03230280413281425), (4464, 0.032300634015023234), (4248, 0.032246231131059615), (912, 0.03224469415730032), (3746, 0.03211558997043321), (1462, 0.032057140709391044), (4211, 0.03202490997902134), (3073, 0.032004764263027556), (4406, 0.03199925428296081), (3443, 0.03199538198783903), (46, 0.031983066444332756), (3580, 0.031963453739430575), (1338, 0.03194807195598796), (2518, 0.03193201548702304), (2954, 0.03191259047953348), (2402, 0.03189509057425394), (4214, 0.031879185437009044), (2201, 0.03186076094341818), (1349, 0.031855646565457515), (2015, 0.03184913596955252), (3723, 0.03183348247037774), (3303, 0.031814352385343796), (3172, 0.03180485450054231), (1249, 0.031791006154310006), (4208, 0.031786954692634685), (3592, 0.03178566592366838), (656, 0.03178278150354368), (2207, 0.03173118869430825), (1169, 0.0317042730569881), (4472, 0.03167179307623371), (285, 0.031653686180906845), (937, 0.03164912856689079), (1212, 0.03163430920978142), (3705, 0.03162596501867517), (1933, 0.03161957351038719), (3951, 0.03160854164213765), (478, 0.03159329614188504), (2065, 0.03156719924477632), (2031, 0.031538510993865246), (3019, 0.03153534241252187), (1558, 0.03150630973356732), (2641, 0.031392175890923114), (1767, 0.03133974838455723), (1347, 0.031332162911774694), (189, 0.03132764652649063), (4431, 0.03127196629874481), (2830, 0.03124892590079084), (3101, 0.03123525171568496), (3954, 0.031207797780164945), (2781, 0.031177166394363444), (2117, 0.031157691438717394), (4169, 0.031148393329454436), (1229, 0.03113848469580004), (1657, 0.03107838263170205), (1442, 0.031053437784095233), (3360, 0.03104540890801024), (902, 0.031033042587541887), (4022, 0.031001761031795083), (2631, 0.030981756839998462), (3054, 0.030953515119928013), (4037, 0.030905671749512822), (1755, 0.030867871585968366), (1108, 0.030867717830895883), (867, 0.03081104381343608), (873, 0.03078773049168443), (1631, 0.030776011816160104), (1843, 0.030724978886547682), (107, 0.030723709758193343), (2311, 0.030689184386453863), (924, 0.03067738018386471), (4101, 0.030645522814998407), (2496, 0.03064

In [ ]:
print('Top 30 Movies Suggested for You: \n')

i=1

for movie in Sorted_Similar_Movies:

  index=movie[0]

  title_from_index=df[df.index==index]['Movie_Title'].values[0]

  if(i<31):

    print(i,'.',title_from_index)
    i+=1

Top 30 Movies Suggested for You:

1 . Somewhere in Time
2 . Beyond the Black Rainbow
3 . Million Dollar Baby
4 . The Hobbit: The Desolation of Smaug
5 . Dune
6 . Showgirls
7 . Hart's War
8 . Men in Black 3
9 . Epic
10 . Project Almanac
11 . A Mighty Wind
12 . Lucky Break
13 . In Time
14 . Silent Running
15 . Heavy Metal
16 . Timecop
17 . The Golden Compass
18 . Superman II
19 . Time Changer
20 . WALL·E
21 . Superman
22 . Jaws 2
23 . Hot Tub Time Machine
24 . Krull
25 . Just Visiting
26 . Bulletproof Monk
27 . Warriors of Virtue
28 . Teenage Mutant Ninja Turtles III
29 . The Book Thief
30 . Wolf

In [ ]:
Movie_Name=input(' Enter your favourite movie name:')

list_of_all_titles=df['Movie_Title'].tolist()

Find_Close_Match= difflib.get_close_matches(Movie_Name, list_of_all_titles)

Close_Match=Find_Close_Match[0]

Index_of_Movie=df[df.Movie_Title==Close_Match] ['Movie_ID'].values[0]

Recommendation_Score=list(enumerate(Similarity_Score[Index_of_Movie]))

sorted_similar_movies=sorted(Recommendation_Score, key=lambda x:x[1], reverse=True)

print("Top 10 Movies suggested for you: \n")
i=1

for movie in sorted_similar_movies:

  index=movie[0]

  title_from_index=df[df.Movie_ID==index]['Movie_Title'].values

  if (i<11):

    print(i, '.',title_from_index)

    i+=1

 Enter your favourite movie name:Kadamba
Top 10 Movies suggested for you:

1 . ['La Bamba']
2 . ['Walking and Talking']
3 . ['Walk the Line']
4 . ['Jumping the Broom']
5 . ['Close Encounters of the Third Kind']
6 . ['Dragon Hunters']
7 . ['The Girl Next Door']
8 . ['I Am Love']
9 . ['Paddington']
10 . ['That Awkward Moment']